# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/TFG/_proyecto/fft_reamp/base.xdc

# Block Designs: bd/fft_reamp/fft_reamp.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp || ORIG_REF_NAME==fft_reamp} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_processing_system7_0_0/fft_reamp_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_processing_system7_0_0 || ORIG_REF_NAME==fft_reamp_processing_system7_0_0} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_xbar_0/fft_reamp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_xbar_0 || ORIG_REF_NAME==fft_reamp_xbar_0} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_ps7_0_axi_periph_0/fft_reamp_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_ps7_0_axi_periph_0 || ORIG_REF_NAME==fft_reamp_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_rst_ps7_0_100M_0/fft_reamp_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_rst_ps7_0_100M_0 || ORIG_REF_NAME==fft_reamp_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_xbar_1/fft_reamp_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_xbar_1 || ORIG_REF_NAME==fft_reamp_xbar_1} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_axi_mem_intercon_0/fft_reamp_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_axi_mem_intercon_0 || ORIG_REF_NAME==fft_reamp_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_xfft_0_0/fft_reamp_xfft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_xfft_0_0 || ORIG_REF_NAME==fft_reamp_xfft_0_0} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_axi_dma_0_0/fft_reamp_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_axi_dma_0_0 || ORIG_REF_NAME==fft_reamp_axi_dma_0_0} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_axi_dma_0_1/fft_reamp_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_axi_dma_0_1 || ORIG_REF_NAME==fft_reamp_axi_dma_0_1} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_datos_dma_0/fft_reamp_datos_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_datos_dma_0 || ORIG_REF_NAME==fft_reamp_datos_dma_0} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_AXI_Gain_0_0/fft_reamp_AXI_Gain_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_AXI_Gain_0_0 || ORIG_REF_NAME==fft_reamp_AXI_Gain_0_0} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_AXI_Rectification_0_0/fft_reamp_AXI_Rectification_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_AXI_Rectification_0_0 || ORIG_REF_NAME==fft_reamp_AXI_Rectification_0_0} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_gain_dma_0/fft_reamp_gain_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_gain_dma_0 || ORIG_REF_NAME==fft_reamp_gain_dma_0} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_axi_dma_0_2/fft_reamp_axi_dma_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_axi_dma_0_2 || ORIG_REF_NAME==fft_reamp_axi_dma_0_2} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_rect_dma_0/fft_reamp_rect_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_rect_dma_0 || ORIG_REF_NAME==fft_reamp_rect_dma_0} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_AXI_Clip_0_0/fft_reamp_AXI_Clip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_AXI_Clip_0_0 || ORIG_REF_NAME==fft_reamp_AXI_Clip_0_0} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_auto_pc_0/fft_reamp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_auto_pc_0 || ORIG_REF_NAME==fft_reamp_auto_pc_0} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_auto_us_0/fft_reamp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_auto_us_0 || ORIG_REF_NAME==fft_reamp_auto_us_0} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_auto_us_1/fft_reamp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_auto_us_1 || ORIG_REF_NAME==fft_reamp_auto_us_1} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_auto_us_2/fft_reamp_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_auto_us_2 || ORIG_REF_NAME==fft_reamp_auto_us_2} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_auto_us_3/fft_reamp_auto_us_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_auto_us_3 || ORIG_REF_NAME==fft_reamp_auto_us_3} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_auto_us_4/fft_reamp_auto_us_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_auto_us_4 || ORIG_REF_NAME==fft_reamp_auto_us_4} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_auto_us_5/fft_reamp_auto_us_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_auto_us_5 || ORIG_REF_NAME==fft_reamp_auto_us_5} -quiet] -quiet

# IP: bd/fft_reamp/ip/fft_reamp_auto_pc_1/fft_reamp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_reamp_auto_pc_1 || ORIG_REF_NAME==fft_reamp_auto_pc_1} -quiet] -quiet

# XDC: d:/TFG/_proyecto/fft_reamp/fft_reamp.gen/sources_1/bd/fft_reamp/fft_reamp_ooc.xdc
