# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/TFG/_proyecto/fft_reamp/fft_reamp.srcs/sources_1/bd/fft_reamp/ip/fft_reamp_processing_system7_0_0/fft_reamp_processing_system7_0_0.xci
# IP: The module: 'fft_reamp_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/TFG/_proyecto/fft_reamp/fft_reamp.gen/sources_1/bd/fft_reamp/ip/fft_reamp_processing_system7_0_0/fft_reamp_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_reamp_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/TFG/_proyecto/fft_reamp/fft_reamp.srcs/sources_1/bd/fft_reamp/ip/fft_reamp_processing_system7_0_0/fft_reamp_processing_system7_0_0.xci
# IP: The module: 'fft_reamp_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/TFG/_proyecto/fft_reamp/fft_reamp.gen/sources_1/bd/fft_reamp/ip/fft_reamp_processing_system7_0_0/fft_reamp_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_reamp_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
